name: echo hogeとecho fugaの間に承認挟むだけ
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  get-versions:
    uses: ./.github/workflows/versions.yml

  echo-hoge:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix-versions) }}
    steps:
      - run: echo ${{matrix.version}}

  echo-fuga:
    needs: [get-versions, echo-hoge]
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix-versions) }}
    environment:
      name: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{matrix.version}}