name: matrixの共通化test
on:
  push:
    branches:
      - main
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=$(cat << 'EOF' | jq -c
          {
            "go": ["1.23"],
            "ruby": ["3.3", "3.4"]
          }
          EOF
          )" >> $GITHUB_OUTPUT
  echo-hoge:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    steps:
      - name: Echo version
        run: echo "hoge (Go ${{ matrix.go }}, Ruby ${{ matrix.ruby }})"
  echo-fuga:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    steps:
      - name: Echo version
        run: echo "fuga (Go ${{ matrix.go }}, Ruby ${{ matrix.ruby }})"
