name: echo hogeとecho fugaの間に承認挟むだけ
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=$(cat << 'EOF' | jq -c
          {
            "go": ["1.23"],
            "ruby": ["3.3", "3.4"]
          }
          EOF
          )" >> $GITHUB_OUTPUT
  echo-hoge:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    steps:
      - name: Echo version
        run: echo ${{matrix.version}}
  echo-fuga:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    steps:
      - name: Echo version
        run: echo ${{matrix.version}}