name: echo hogeとecho fugaの間に承認挟むだけ
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(cat matrix.json | jq -c)" >> $GITHUB_OUTPUT
        working-directory: .github/workflows/
  echo-hoge:
    name: test (Go ${{ matrix.go }}, Ruby ${{ matrix.ruby }})
    needs:
      - generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Echo version
        run: echo ${{matrix.version}}