name: echo hogeとecho fugaの間に承認挟むだけ
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  echo-hoge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - run: echo ${{matrix.version}}
  echo-fuga:
    needs: echo-hoge
    environment:
      name: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "fuga"
