name: Common Versions
on:
  workflow_call: {}

jobs:
  provide-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix-versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-versions
        shell: bash
        run: |
          echo "versions=$(jq -n --arg v "[10,12,14]" "$v")" >> $GITHUB_OUTPUT 